class_name: Container
# For basic Megatron-LM training, use the ROCm Primus image. This one is an extension with linear_flash_attention and a few other packages.
image: /shared_silo/scratch/containers/rocm_primus_v25.11_transformers-4.5.7_linear_FA.sif
# image: /shared_silo/scratch/containers/build-rocm_primus_v25.11_transformers-5.5.4_linear_FA/rocm_primus_v25.11_transformers-5.5.4_linear_FA.sif
runtime: apptainer

bind:
  - "/shared_silo/scratch"
  - "${oc.env:PWD}"
  - "/shared_silo/scratch/dzautner/rocm71_signalpool_fix/libamdhip64.so.7.1-3ad064d:/opt/venv/lib/python3.10/site-packages/torch/lib/libamdhip64.so"
  - "/shared_silo/scratch/dzautner/rocm71_signalpool_fix/libamdhip64.so.7.1-3ad064d:/opt/venv/lib/python3.10/site-packages/torch/lib/libamdhip64.so.7"

pwd: ${oc.env:PWD}
env:
  WANDB_MODE: "offline"
  MACHINE_NAME: "MI325X"
  PYTHONPATH: "."
python: "python3"
